### ISSUE TITLE
내 게임 기록 불러오기 api 구현 필요

### ISSUE THREAD

**Issue by leesiha** [five-ducks/heron#24]
> 게임과 관련된 코드라서 나중에 추가될 것으로 예상됩니다. 이후 함께 작업하면 될 것 같습니다.
> 프론트와 백 모두 관련된 작업이라서, 까먹지 않기 위해 이슈 올립니다.

현재 front-end code입니다. 
```c++
// frontend/src/store/game.js
export default store;

export const loadGameRecords = async () => {
	try {
		const response = await fetch('https://localhost/src/temp/gameRecords.json');
		store.state.gameRecords = await response.json();
	} catch (error) {
		console.error('Error loading game records:', error);
	}
}
```
- 임시로 만들어둔 목 데이터 (`frontend/src/temp/gameRecords.json`에 저장해둔) 파일을 읽어와서 화면에 띄우고 있습니다.
  <img width="1512" alt="스크린샷 2024-10-03 오후 7 15 00" src="https://github.com/user-attachments/assets/c1d032eb-164a-4e76-a18a-04a0991926e0">
- http://localhost:8000/docs/ 를 확인해보면,
  - `GET` `/users/self/`
    <img width="189" alt="스크린샷 2024-10-03 오후 7 18 47" src="https://github.com/user-attachments/assets/ad89c81b-79ba-435c-a571-12651f344fb8">
  - `GET` `/users/self/friends/`
    <img width="388" alt="스크린샷 2024-10-03 오후 7 19 12" src="https://github.com/user-attachments/assets/5b567e0c-3332-4b33-9906-44b3334716e9">

친구들의 매치 기록은 불러오는데, 유저의 매치 기록은 불러오지 않고 있습니다.

**Comment by nuyheat** [comment]
기능은 구현이 되었는데 docs가 수정되지 않았습니다!

현재 users/self로 경기기록을 얻어올 수 있습니다.

추우에 pr시 반영 해놓도록 하겠습니다!

**Comment by leesiha** [comment]
오호 있었군요! 바로 작업 하면 되겠네요! 알겠습니다

**Comment by leesiha** [comment]
<img width="1512" alt="스크린샷 2024-10-03 오후 9 31 26(2)" src="https://github.com/user-attachments/assets/5eb01503-3d0b-4776-a79d-cae64ed6fe78">

1. user1_name, user2_name 이 없어서, backend에서 수정해놓겠습니다. 추후 PR 확인해주세요
2. username1_grade -> user1_grade, username2_grade -> user2_grade 로 변경하겠습니다.
