### ISSUE TITLE
api 수정 요청

### ISSUE THREAD

**Issue by sunsetfactory** [five-ducks/heron#32]
## 현재 매치 데이터 문제

현재 매치 데이터에 사용자 이미지가 전달되지 않아 모두 피카츄로 표시되고 있습니다. 추가 부탁드립니다.

![매치 데이터 문제]
<img width="601" alt="Screen Shot 2024-10-17 at 3 31 54 PM" src="https://github.com/user-attachments/assets/41c5e14e-e92a-460a-be6a-c73a79741d70">

![대체 이미지](https://github.com/user-attachments/assets/c9475a98-3070-44a9-a140-b7bd045b139d)

---

## 친구 정보창 개선 요청

친구 정보창에서 레벨과 승률을 표현하기 위해 `wincnt`, `losecnt`, `exp`가 필요합니다. 추가 부탁드립니다.

![친구 정보창](https://github.com/user-attachments/assets/ae71d58f-9936-440c-8026-b94811129245)

**Comment by nuyheat** [comment]
수정완료 되었습니다!
